### PR TITLE
Input validation for property value

### LINKED ISSUE #446: [BUG] Updating/Visualizing a property of type double
**Describe the bug**
If you update a property value of type ‘double’ via API and then visualize it over the AAS GUI, something strange happens.

1. When a string (here "test_data") is sent that cannot be converted to a double, the AAS UI displays the value in the submodel overview but not when the property is selected. See screenshot 1 and 2.
2. When a string (here "123") is sent that can be converted to a double, the AAS UI displays the value in the submodel overview and also when the property is selected. See screenshot 3 and 4.

**To Reproduce**
Executed command: PATCH /submodels/{submodelIdentifier}/submodel-elements/{idShortPath}/$value through swaggerhub

**Expected behavior**
The property values displayed should be concise.

**BaSyx (please complete the following information):**
I am running the very latest version of Basyx AAS Env as well as the latest AAS GUI.

**Screenshots**

Screenshot 1:
Image

Screenshot 2:
Image

Screenshot 3:
Image

Screenshot 4:
Image

### PR DESCRIPTION
**Pull request by seicke**
## Description of Changes

This PR adds validation for property value input field.
Note: Unfortunately, I haven't found an adequate js library for checking a string regarding xs data types.

This PR fixes also a bug, where updated props of SMEs will not be shown in the SubmodelElementView after clicking the save button (router.push of an unchanged path does not cause a new fetching and dipatching of the selected SME, explicit fetch and dispatch needed).

This PR also fixes the components.d.ts regarding the deleted components of PR #612.

## Related Issue
Closes #446

### CODE REVIEW

File: aas-web-ui/src/components/EditorComponents/SubmodelElements/PropertyForm.vue [hunk 1]
```diff
@@ -197,7 +224,346 @@
...
+
+                case 'String':
+                default:
+                    break;
+            }
+        }
+
+        propertyValueErrorMessage.value = null;
+        return true;
+    }
```
Comment (aaronzi) [inline aas-web-ui/src/components/EditorComponents/SubmodelElements/PropertyForm.vue:560]: Could you please extract this validation into separate util functions? This reduces the size of the propertyForm component and makes the functionality reusable (e.g. for the different valuesTypes of Properties in the normal SubmodelElementView)

**Review by aaronzi — CHANGES_REQUESTED** [review]
Thanks for this PR. This is a very useful addition to the BaSyx UI. I added one remark to the PropertyForm component.

**Review by aaronzi — APPROVED** [review]
