### PR TITLE
Preserve query parameter for switching between AAS Viewer/Editor and Submodel Viewer

### LINKED ISSUE #166: [BUG] Preserve query parameter for switching between AAS Editor / AAS Viewer / About Page
**Describe the bug**
Switiching between AAS Editor / AAS Viewer / About page does not preserve query parameter `aas` and `path`.

**To Reproduce**
1. Opening aas-gui
2. Selecting and AAS from the AAS List
3. Goto menu, click on AAS Viewer

**Expected behavior**
If an AAS is selected, clicking on AAS Editor / AAS Viewer / About menupoint will preserver selected AAS.
This is very important in the case of activated `singleAas` feature!

### PR DESCRIPTION
**Pull request by seicke**
Preserving of query parameter was realised with route guard in combination with a new query state in the navigation store.

- To use the navigation store in the `route.ts` the order of `app.use(pinia)` and `app.use(router)` in `main.ts` had to be adapted.
- Within the route guard it is necessary to fetch and dispatch the AAS/SME with respect to the preserved query parameter.

Fetching and dispatching of AAS was already outsourced in the AAS repository client and could be used easily. An equivalent function for fetching and dispatching of SME has been missing so far and was implemented in SMRepositoryClient.

This PR also adapted `App.vue` regarding the usage of the new functionality `fetchAndDispatchSme()` to simplify code readability.

Closes #166

### CODE REVIEW

File: aas-web-ui/src/router.ts [hunk 1]
```diff
@@ -24,13 +27,47 @@ const routes = [
...
+                    next(updatedRoute);
+                    if (query.aas) await fetchAndDispatchAas(query.aas as string);
+                    if (query.path) await fetchAndDispatchSme(query.path as string);
+                    return;
+                }
+            }
+        }
+        next();
+    });
+
```
Comment (aaronzi) [inline aas-web-ui/src/router.ts:71]: When switching from either the AAS Viewer or the AAS Editor to the Submodel Viewer, the idShortPath (`/submodel-elements/...`) should be stripped from the `path` query parameter.

File: aas-web-ui/src/App.vue [hunk 2]
```diff
@@ -148,35 +145,4 @@
             router.push({ name: 'AASViewer', query });
         }
     }
```
Comment (aaronzi) [inline aas-web-ui/src/App.vue:147]: Do you think that this functionality should be handled be the route guard and moved to it in this PR?

Comment (seicke) [reply aas-web-ui/src/App.vue:147]: I agree with you that the handling of the mobile and desktop view should be done within the route guard, but I would like to do this in a separate PR. Topic is saved as ticket, see https://github.com/eclipse-basyx/basyx-aas-web-ui/issues/225

**Review by aaronzi — APPROVED** [review]
